name: Идея улучшения
description: Предложение фичи или документации
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Задача или боль
      description: Какую проблему решаем?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Предложение
      description: Как вы это видите (кратко)?
    validations:
      required: true
