"""add table reviews 

Revision ID: 010830ad6d9b
Revises: a2916974de79
Create Date: 2025-03-28 21:55:27.575816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010830ad6d9b'
down_revision: Union[str, None] = 'a2916974de79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_wash_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_wash_id'], ['car_washes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('car_washes', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('car_washes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('car_washes', sa.Column('rating', sa.Float(), server_default=sa.text('0.0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_washes', 'rating')
    op.drop_column('car_washes', 'description')
    op.drop_column('car_washes', 'photo_url')
    op.drop_table('reviews')
    # ### end Alembic commands ###
