"""add wash_posts table

Revision ID: 0efb3e894b73
Revises: 676ca1b2c97b
Create Date: 2025-03-24 23:09:59.145141

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0efb3e894b73"
down_revision: Union[str, None] = "676ca1b2c97b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wash_posts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("car_wash_id", sa.Integer(), nullable=False),
        sa.Column("post_number", sa.Integer(), nullable=True),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["car_wash_id"], ["car_washes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("car_wash_id", "post_number", name="uq_post_number"),
    )
    op.add_column("car_washes", sa.Column("work_start", sa.String(), nullable=True))
    op.add_column("car_washes", sa.Column("work_end", sa.String(), nullable=True))
    op.add_column("car_washes", sa.Column("work_days", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("car_washes", "work_days")
    op.drop_column("car_washes", "work_end")
    op.drop_column("car_washes", "work_start")
    op.drop_table("wash_posts")
    # ### end Alembic commands ###
