"""add token column

Revision ID: 139e83fdb2ce
Revises: 1b8f9c0ddbf7
Create Date: 2025-03-28 22:40:55.814350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139e83fdb2ce'
down_revision: Union[str, None] = '1b8f9c0ddbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_washes', sa.Column('token', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_washes', 'token')
    # ### end Alembic commands ###
