"""add owner column

Revision ID: 1b8f9c0ddbf7
Revises: 010830ad6d9b
Create Date: 2025-03-28 22:08:17.719629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8f9c0ddbf7'
down_revision: Union[str, None] = '010830ad6d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('owner', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'owner')
    # ### end Alembic commands ###
