"""remove unique constraint from car_number2

Revision ID: 623006b825c6
Revises: cd72d59e81fe
Create Date: 2025-03-29 14:43:20.188938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623006b825c6'
down_revision: Union[str, None] = 'cd72d59e81fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_car_number', 'users_autos', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_car_number', 'users_autos', ['car_number'])
    # ### end Alembic commands ###
