"""add owner

Revision ID: 6a73eb2abaae
Revises: 0efb3e894b73
Create Date: 2025-03-24 23:22:40.050936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a73eb2abaae'
down_revision: Union[str, None] = '0efb3e894b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_washes', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'car_washes', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.alter_column('wash_posts', 'post_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wash_posts', 'post_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'car_washes', type_='foreignkey')
    op.drop_column('car_washes', 'owner_id')
    # ### end Alembic commands ###
