"""add wash_time

Revision ID: 99b3489f1fe7
Revises: be8593604830
Create Date: 2025-03-04 08:21:23.524336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b3489f1fe7'
down_revision: Union[str, None] = 'be8593604830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('wash_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'wash_time')
    # ### end Alembic commands ###
