"""add table booking

Revision ID: a2916974de79
Revises: 6a73eb2abaae
Create Date: 2025-03-26 22:55:10.842354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2916974de79'
down_revision: Union[str, None] = '6a73eb2abaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_wash_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_auto_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.String(), nullable=False),
    sa.Column('booking_time', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('price_at_booking', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_wash_id'], ['car_washes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['wash_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['car_wash_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_auto_id'], ['users_autos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
