"""add wash_time_complex

Revision ID: bd71527489c9
Revises: 99b3489f1fe7
Create Date: 2025-03-04 08:23:46.064476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd71527489c9'
down_revision: Union[str, None] = '99b3489f1fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('wash_time_complex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'wash_time_complex')
    # ### end Alembic commands ###
