"""remove unique constraint from car_number

Revision ID: cd72d59e81fe
Revises: 139e83fdb2ce
Create Date: 2025-03-29 14:37:07.799567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd72d59e81fe'
down_revision: Union[str, None] = '139e83fdb2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_autos', 'car_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_autos', 'car_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
