"""new_tables

Revision ID: cdd39ce6bb99
Revises: 116cc47f5113
Create Date: 2025-03-23 17:12:50.352325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd39ce6bb99'
down_revision: Union[str, None] = '116cc47f5113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_washes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('busy', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_wash_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_wash_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_wash_id'], ['car_washes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('models_mark_id_fkey', 'models', type_='foreignkey')
    op.create_foreign_key(None, 'models', 'brands', ['mark_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_autos_brand_id_fkey', 'users_autos', type_='foreignkey')
    op.drop_constraint('users_autos_user_id_fkey', 'users_autos', type_='foreignkey')
    op.drop_constraint('users_autos_model_id_fkey', 'users_autos', type_='foreignkey')
    op.create_foreign_key(None, 'users_autos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_autos', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_autos', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_autos', type_='foreignkey')
    op.drop_constraint(None, 'users_autos', type_='foreignkey')
    op.drop_constraint(None, 'users_autos', type_='foreignkey')
    op.create_foreign_key('users_autos_model_id_fkey', 'users_autos', 'models', ['model_id'], ['id'])
    op.create_foreign_key('users_autos_user_id_fkey', 'users_autos', 'users', ['user_id'], ['id'])
    op.create_foreign_key('users_autos_brand_id_fkey', 'users_autos', 'brands', ['brand_id'], ['id'])
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.create_foreign_key('models_mark_id_fkey', 'models', 'brands', ['mark_id'], ['id'])
    op.drop_table('car_wash_services')
    op.drop_table('services')
    op.drop_table('car_washes')
    # ### end Alembic commands ###
